apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-security-context
spec:
  rules:
    - name: require-security-context
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Security context must be defined for all containers."
        pattern:
          spec:
            containers:
              - securityContext: {}
